### PR TITLE
Streamlining top-level ALARA output parser

### PR DESCRIPTION
**Pull request by gonuke**
This includes the refactoring we did together in the S/W to streamline the parser

### CODE REVIEW

**Comment by zxkjack123** [comment]
It fails the test, debugging ...

**Comment by gonuke** [comment]
Sorry I didn't run the tests...

**Comment by gonuke** [comment]
I found a line that wasn't correct, maybe that will fix the tests?

**Comment by zxkjack123** [comment]
@gonuke Yes, that fixed the problem.

**Pull request merged**
