### PR TITLE
Python3 compatible fix r2s

### PR DESCRIPTION
**Pull request by zxkjack123**
I meet a problem with a test function in `test_r2s.py`: test_irradiation_setup_unstructured_nondef_tag().
The tag of 'TALLY_TAG' was set to the default value.  For the convenience of debugging, I reformed this  PR:
- Commented other tests in test_r2s except for `est_irradiation_setup_unstructured_nondef_tag()`
- Reformed the `test_irradiation_setup_unstructured_nondef_tag()`, do not use multiprocessing
- Add a `pdb.set_trace()` in `mesh.py` at a key point

The following contents list the call graph of lines causing the error:
```
-> self.test(*self.arg)
  /root/opt/pyne/tests/test_r2s.py(364)test_irradiation_setup_unstructured_nondef_tag()
-> results = irradiation_setup_unstructured("TALLY_TAG")
  /root/opt/pyne/tests/test_r2s.py(212)irradiation_setup_unstructured()
-> output_material=output_material)
  /root/.local/lib/python3.6/site-packages/pyne/r2s.py(131)irradiation_setup()
-> m = resolve_mesh(flux_mesh, tally_num, flux_tag, output_material)
  /root/.local/lib/python3.6/site-packages/pyne/r2s.py(48)resolve_mesh()
-> m = Mesh(structured=False, mesh=mesh_reference)
> /root/.local/lib/python3.6/site-packages/pyne/mesh.py(874)__init__()
-> setattr(self, name, NativeMeshTag(mesh=self, name=name))
  /root/.local/lib/python3.6/site-packages/pyne/mesh.py(929)__setattr__()
-> def __setattr__(self, name, value):
```

I found the place where the code went wrong, but I failed to fix it.

### CODE REVIEW

**Comment by zxkjack123** [comment]
Any suggestions about how to fix this problem? @gonuke, @pshriwise, @bam241

**Comment by pshriwise** [comment]
I only had a few minutes to look this over tonight, but my initial guess is that it is a failed dictionary key lookup in `mesh.__setattr__`. I think `_lazy_args` could exist without having the keys that method assumes it does. If you look at the `NatveMeshTag.__init__` [method](https://github.com/zxkjack123/pyne/blob/5836eaf37fec3ae060b1163c9af966925e4a3581/pyne/mesh.py#L336), when those parameters are passed in, _lazy_args exists but is not modified. There is likely something inconsistent about the behavior there.

**Comment by zxkjack123** [comment]
> I only had a few minutes to look this over tonight, but my initial guess is that it is a failed dictionary key lookup in `mesh.__setattr__`. I think `_lazy_args` could exist without having the keys that method assumes it does. If you look at the `NatveMeshTag.__init__` [method](https://github.com/zxkjack123/pyne/blob/5836eaf37fec3ae060b1163c9af966925e4a3581/pyne/mesh.py#L336), when those parameters are passed in, _lazy_args exists but is not modified. There is likely something inconsistent about the behavior there.

The '_lazy_args' doesn't exist in this case.

**Comment by zxkjack123** [comment]
Found that this unit test function actually disabled two years ago by @makeclean in this PR:https://github.com/pyne/pyne/commit/8b8fc8be8e95d046a47be4eabbbd3f679486e203

I decide to keep it as unchanged for this unit test function.
@makeclean do you remember why disable this unit tests? Is `nondef_tag` still supported or not?

**Pull request merged**
